import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Lang = "en" | "fr";

const dictionary = {
  en: {
    nav: { home: "Home", about: "About", projects: "Projects", articles: "Articles", demos: "Demos", experience: "Experience", insights: "Insights", contact: "Contact", resume: "Resume / CV" },
    heroTitle: "Building reliable data systems that turn complexity into decisions.",
    heroText: "Data Engineer and BI Builder focused on scalable pipelines, cloud data warehouses, analytics automation, and business intelligence solutions.",
    explore: "Explore My Work",
    contact: "Contact Me",
    cv: "Download CV",
    available: "Open to Data & BI Opportunities",
    dataDriven: "Let's build something data-driven.",
    send: "Send Message",
    success: "Message sent. Thanks for reaching out.",
    error: "Something went wrong. Please try again.",
    caseStudy: "View Case Study",
    readArticle: "Read Article",
    all: "All",
    impactEyebrow: "Impact",
    impactTitle: "Evidence-oriented work, ready for verified metrics.",
    projectsEyebrow: "Selected Work",
    projectsTitle: "Featured data systems and analytics products.",
    architectureEyebrow: "Architecture",
    architectureTitle: "From Raw Data to Decision",
    skillsEyebrow: "Skills",
    skillsTitle: "Technical matrix across data and product delivery.",
    experienceEyebrow: "Experience",
    experienceTitle: "A practical path through BI, data engineering, and applied analytics.",
    insightsEyebrow: "Insights",
    insightsTitle: "Technical notes and future research directions.",
    modelEyebrow: "Operating Model",
    modelTitle: "A more solid model for how the work is delivered.",
    modelItems: [
      "Discovery: define business questions, stakeholders, sources, and risks.",
      "Data foundation: profile sources, model entities, and document ownership.",
      "Pipeline delivery: automate extraction, validation, transformation, and monitoring.",
      "Decision layer: publish semantic models, dashboards, and explainable KPI definitions.",
      "Iteration: improve quality controls, performance, documentation, and user adoption."
    ],
    impactItems: ["Automated reporting workflows", "Built BI dashboards for operational decision-making", "Designed ETL pipelines from SQL Server to cloud warehousing", "Worked with large operational datasets", "Reduced manual processing time through automation", "Improved reporting consistency through validation controls"],
    aboutTitle: "Data engineering discipline with product-builder range.",
    aboutBody: "Hamza Bakh is a Data Engineer and BI-oriented technology professional focused on building reliable data pipelines, warehouse architectures, automation workflows, and decision-support systems.",
    aboutValues: "Clarity, validation, maintainability, business context, accessible interfaces, and honest evidence. The site avoids unverified metrics and keeps content editable through the admin dashboard.",
    contactIntro: "For recruiters, founders, collaborators, and research contacts. Share the role, project context, data stack, and timeline so the conversation starts with useful signal.",
    resumeTitle: "Hamza Bakh — Data Engineer | Data Analyst | BI Developer",
    resumeIntro: "A PDF can be placed at public/Hamza-Bakh-CV.pdf. The button remains stable for deployment and recruiter sharing.",
    privacyTitle: "Privacy policy",
    privacyBody: "Contact form submissions are stored securely for professional follow-up. Messages include the information you provide: name, email, organization, subject, and message.",
    formName: "Full name",
    formEmail: "Email",
    formCompany: "Company / Organization",
    formSubject: "Subject",
    formMessage: "Message",
    privacy: "Privacy",
    notFound: "This page is not in the pipeline.",
    backHome: "Back Home",
    ui: {
      heroHeadlineTop: "I build the layer",
      heroHeadlineBottom: "businesses",
      heroHeadlineEmphasis: "trust.",
      portfolioArchitecture: "Portfolio architecture",
      portfolioArchitectureTitle: "A clear path from proof to conversation.",
      portfolioSystemMap: "Portfolio system map",
      portfolioSystemNote: "Every route has a purpose: orient, prove, explain, or start a useful conversation.",
      portfolioRoot: "Portfolio",
      liveLab: "Live engineering lab",
      liveLabTitle: "Run the systems. See every output.",
      liveLabIntro: "Five deterministic demonstrations run entirely in your browser with synthetic data. Choose one, change the scenario, then press the bright",
      noSetup: "No setup required",
      safeSynthetic: "Safe synthetic data",
      startRecommended: "Start recommended demo",
      launchDemo: "Launch interactive demo",
      projectsEyebrow: "Portfolio",
      projectsPageTitle: "Projects built around pipelines, dashboards, automation, and decisions.",
      loadingCaseStudy: "Loading case study...",
      allProjects: "Projects",
      caseStudyStructure: "Case study structure",
      caseStudyFlow: "Problem → Solution → Architecture → Stack → Demo → Results.",
      problem: "Problem",
      solution: "Solution",
      architecture: "Architecture",
      techStack: "Tech stack",
      liveDemo: "Live demo",
      results: "Results",
      runSyntheticDemo: "Run the synthetic browser demo and inspect each pipeline stage.",
      readCaseStudy: "Read the case study and contact Hamza for a guided walkthrough.",
      context: "Context",
      businessContext: "Business context, challenge, and objectives.",
      challenge: "Challenge",
      technicalImplementation: "Technical implementation",
      resultsOutcomes: "Results and outcomes",
      dataFlow: "Data flow",
      architectureQuality: "Architecture and quality approach.",
      launchInteractive: "Launch interactive demo",
      inspectPipeline: "Inspect the pipeline with synthetic data.",
      engineeringDecisions: "Engineering decisions",
      engineeringDecisionsTitle: "Security, validation, and future improvements.",
      dataModelOverview: "Data model overview",
      qualityValidation: "Quality and validation",
      qualityValidationBody: "Schema checks, duplicate controls, freshness checks, KPI reconciliation, and manual review queues where needed.",
      futureImprovements: "Future improvements",
      futureImprovementsBody: "Add lineage views, automated anomaly detection, richer observability, and production dashboard screenshots when approved.",
      next: "Next",
      similarSystem: "Interested in a similar system?",
      contactHamza: "Contact Hamza",
      interactiveExperience: "Interactive experience",
      runInspect: "Run the system, inspect the result.",
      engineeringContext: "Engineering context",
      problemSolutionValue: "Problem, solution, business value.",
      engineeringSolution: "Engineering solution",
      engineeringSolutionBody: "Explicit stages, deterministic transformations, validation gates and readable outputs keep the demo close to a real workflow.",
      businessValue: "Business value",
      nextStep: "Next step",
      similarDataProblem: "Have a similar data problem?",
      discussProject: "Discuss a project",
      demoNotFound: "Demo not found",
      backToDemos: "Back to demos",
      allDemos: "All demos",
      sourcePrivate: "Source code private; the browser demo is safe and synthetic.",
      demoShell: "DemoShell",
      pipelineSimulation: "pipeline simulation",
      browserLogic: "browser logic",
      syntheticDataset: "Demonstration dataset — synthetic · no external credentials",
      running: "Running",
      warning: "Warning",
      ready: "Ready",
      tenant: "Tenant",
      scenario: "Scenario",
      runSimulation: "Run simulation",
      simulationRunning: "Simulation running…",
      reset: "Reset",
      instantResult: "Instant result",
      dataset: "Dataset",
      pipelineStatus: "Pipeline status",
      reviewRequired: "Review required before publication",
      syntheticRun: "Synthetic run completed",
      outputPreview: "Output preview",
      executionLog: "Execution log",
      whatHappened: "What just happened?",
      purpose: "Purpose",
      validation: "Validation",
      outputs: "Outputs",
      linkedinProfile: "LinkedIn verified profile",
      experienceCredentials: "Experience, education and credentials with real source data.",
      headline: "Headline",
      openTo: "Open to",
      viewSource: "View source profile",
      professionalTimeline: "Professional timeline",
      rolesContext: "Roles and delivery context.",
      education: "Education",
      educationFoundation: "The foundation behind the work.",
      certifications: "Certifications",
      learningMilestones: "Verified learning milestones.",
      linkedInProjects: "LinkedIn projects",
      connectedProjects: "Projects connected to the profile.",
      profile: "Profile",
      focusAreas: "Focus areas",
      focusAreasText: "Data Engineering, Business Intelligence, ETL/ELT, SQL, Snowflake, Power BI, Metabase, Python automation, and full-stack product delivery.",
      downloadCv: "Download CV",
      backToPortfolio: "Back to portfolio",
      contactEyebrow: "Contact",
      github: "GitHub",
      linkedin: "LinkedIn",
      email: "Email",
      footerTagline: "Data Engineer | BI Developer | Full-Stack Builder."
      ,homeNode: "Home", aboutNode: "About", projectsNode: "Projects", articlesNode: "Articles", contactNode: "Contact", resumeNode: "Resume / CV", profilesNode: "Profiles",
      firstImpression: "01 · first impression", contextNode: "02 · context", proofOfWork: "03 · proof of work", thinking: "04 · thinking", startConversation: "05 · start a conversation", credentials: "06 · credentials", publicCode: "07 · public code",
      heroSection: "Hero section", valueProposition: "Value proposition", primaryCtas: "Primary CTAs", presentation: "Presentation", experience: "Experience", toolsSkills: "Tools & skills", featuredProjects: "Featured projects", labsInProgress: "Labs / in progress", caseStudies: "Case studies", blogPosts: "Blog posts", researchNotes: "Research notes", tutorials: "Tutorials", message: "Message", collaboration: "Collaboration", workOpportunities: "Work opportunities", onePageCv: "One-page CV", downloadPdf: "Download PDF", githubProfile: "GitHub profile", linkedinProfileLink: "LinkedIn profile", sourceCode: "Source code", runLiveDemos: "Run live demos", followers: "LinkedIn followers", connections: "Professional connections", verifiedRoles: "Verified roles & internships", kicker: "Data engineering · analytics · BI architecture", agadirMorocco: "AGADIR · MOROCCO", openToInternational: "OPEN TO UK + INTERNATIONAL · ON-SITE · HYBRID · REMOTE", values: "Values", privacyAnalytics: "The site may store basic route analytics when the database is configured. No client-side secrets are exposed. Email notifications are sent only when the owner configures an email provider.", presentationBody: "The person behind the systems, principles, and delivery style.", experienceBody: "A timeline of data, BI, analytics, and applied engineering work.", toolsSkillsBody: "The practical stack used across pipelines, warehouses, dashboards, and products.", aboutIntersection: "His work sits at the intersection of operational data, analytics engineering, dashboards, and full-stack applications that make data easier to trust and use.", insightsPageTitle: "Technical articles, notes, and research ideas.", loadingArticle: "Loading article...", rows: "rows", columns: "columns"
    }
  },
  fr: {
    nav: { home: "Accueil", about: "À propos", projects: "Projets", articles: "Articles", demos: "Démos", experience: "Expérience", insights: "Articles", contact: "Contact", resume: "CV" },
    heroTitle: "Construire des systèmes de données fiables qui transforment la complexité en décisions.",
    heroText: "Data Engineer et BI Builder orienté pipelines scalables, entrepôts cloud, automatisation analytique et solutions décisionnelles.",
    explore: "Voir les projets",
    contact: "Me contacter",
    cv: "Télécharger le CV",
    available: "Ouvert aux opportunités Data & BI",
    dataDriven: "Construisons quelque chose avec les données.",
    send: "Envoyer",
    success: "Message envoyé. Merci pour votre prise de contact.",
    error: "Une erreur est survenue. Veuillez réessayer.",
    caseStudy: "Voir l'étude de cas",
    readArticle: "Lire l'article",
    all: "Tous",
    impactEyebrow: "Impact",
    impactTitle: "Un travail fondé sur des preuves, prêt pour des métriques vérifiées.",
    projectsEyebrow: "Projets sélectionnés",
    projectsTitle: "Systèmes data et produits analytiques mis en avant.",
    architectureEyebrow: "Architecture",
    architectureTitle: "De la donnée brute à la décision",
    skillsEyebrow: "Compétences",
    skillsTitle: "Matrice technique entre data, BI et développement produit.",
    experienceEyebrow: "Expérience",
    experienceTitle: "Un parcours pratique entre BI, data engineering et analytique appliquée.",
    insightsEyebrow: "Articles",
    insightsTitle: "Notes techniques et pistes de recherche futures.",
    modelEyebrow: "Modèle de travail",
    modelTitle: "Un modèle plus solide pour livrer les projets.",
    modelItems: [
      "Cadrage : définir les questions métier, les acteurs, les sources et les risques.",
      "Fondation data : profiler les sources, modéliser les entités et documenter la propriété.",
      "Pipelines : automatiser l'extraction, la validation, la transformation et le monitoring.",
      "Couche décisionnelle : publier des modèles sémantiques, dashboards et définitions KPI claires.",
      "Itération : améliorer les contrôles qualité, la performance, la documentation et l'adoption."
    ],
    impactItems: ["Workflows de reporting automatisés", "Dashboards BI pour les décisions opérationnelles", "Pipelines ETL de SQL Server vers le cloud", "Travail sur de grands jeux de données opérationnels", "Réduction du traitement manuel par l'automatisation", "Reporting plus cohérent grâce aux contrôles qualité"],
    aboutTitle: "Discipline data engineering avec une vision de builder produit.",
    aboutBody: "Hamza Bakh est un professionnel orienté Data Engineering et BI, concentré sur les pipelines fiables, les architectures warehouse, l'automatisation et les systèmes d'aide à la décision.",
    aboutValues: "Clarté, validation, maintenabilité, contexte métier, interfaces accessibles et preuves honnêtes. Le site évite les métriques non vérifiées et garde le contenu modifiable depuis l'administration.",
    contactIntro: "Pour les recruteurs, fondateurs, collaborateurs et contacts recherche. Partagez le rôle, le contexte projet, la stack data et le calendrier pour démarrer avec un signal utile.",
    resumeTitle: "Hamza Bakh — Data Engineer | Data Analyst | BI Developer",
    resumeIntro: "Un PDF peut être placé dans public/Hamza-Bakh-CV.pdf. Le bouton reste stable pour le déploiement et le partage avec les recruteurs.",
    privacyTitle: "Politique de confidentialité",
    privacyBody: "Les messages du formulaire sont stockés pour le suivi professionnel. Ils incluent les informations fournies : nom, email, organisation, sujet et message.",
    formName: "Nom complet",
    formEmail: "Email",
    formCompany: "Entreprise / Organisation",
    formSubject: "Sujet",
    formMessage: "Message",
    privacy: "Confidentialité",
    notFound: "Cette page n'est pas dans le pipeline.",
    backHome: "Retour à l'accueil",
    ui: {
      heroHeadlineTop: "Je construis des systèmes",
      heroHeadlineBottom: "data fiables pour",
      heroHeadlineEmphasis: "décider.",
      portfolioArchitecture: "Architecture du portfolio",
      portfolioArchitectureTitle: "Un parcours clair, de la preuve à la conversation.",
      portfolioSystemMap: "Carte du système portfolio",
      portfolioSystemNote: "Chaque route a un objectif : orienter, prouver, expliquer ou démarrer une conversation utile.",
      portfolioRoot: "Portfolio",
      liveLab: "Laboratoire d'ingénierie",
      liveLabTitle: "Lancez les systèmes. Voyez chaque résultat.",
      liveLabIntro: "Cinq démonstrations déterministes s'exécutent dans votre navigateur avec des données synthétiques. Choisissez-en une, changez le scénario, puis appuyez sur",
      noSetup: "Aucune installation",
      safeSynthetic: "Données synthétiques sûres",
      startRecommended: "Démarrer la démo recommandée",
      launchDemo: "Lancer la démo interactive",
      projectsEyebrow: "Portfolio",
      projectsPageTitle: "Des projets construits autour des pipelines, dashboards, automatisations et décisions.",
      loadingCaseStudy: "Chargement de l'étude de cas...",
      allProjects: "Projets",
      caseStudyStructure: "Structure de l'étude de cas",
      caseStudyFlow: "Problème → Solution → Architecture → Stack → Démo → Résultats.",
      problem: "Problème",
      solution: "Solution",
      architecture: "Architecture",
      techStack: "Stack technique",
      liveDemo: "Démo en direct",
      results: "Résultats",
      runSyntheticDemo: "Lancez la démo synthétique et inspectez chaque étape du pipeline.",
      readCaseStudy: "Lisez l'étude de cas et contactez Hamza pour une présentation guidée.",
      context: "Contexte",
      businessContext: "Contexte métier, défi et objectifs.",
      challenge: "Défi",
      technicalImplementation: "Implémentation technique",
      resultsOutcomes: "Résultats et impacts",
      dataFlow: "Flux de données",
      architectureQuality: "Approche architecture et qualité.",
      launchInteractive: "Lancer la démo interactive",
      inspectPipeline: "Inspectez le pipeline avec des données synthétiques.",
      engineeringDecisions: "Choix d'ingénierie",
      engineeringDecisionsTitle: "Sécurité, validation et améliorations futures.",
      dataModelOverview: "Vue du modèle de données",
      qualityValidation: "Qualité et validation",
      qualityValidationBody: "Contrôles de schéma, doublons, fraîcheur, rapprochement des KPI et files de revue manuelle si nécessaire.",
      futureImprovements: "Améliorations futures",
      futureImprovementsBody: "Ajouter la traçabilité, la détection d'anomalies, une observabilité plus riche et des captures de dashboards de production après validation.",
      next: "Suite",
      similarSystem: "Un système similaire vous intéresse ?",
      contactHamza: "Contacter Hamza",
      interactiveExperience: "Expérience interactive",
      runInspect: "Lancez le système, inspectez le résultat.",
      engineeringContext: "Contexte d'ingénierie",
      problemSolutionValue: "Problème, solution, valeur métier.",
      engineeringSolution: "Solution d'ingénierie",
      engineeringSolutionBody: "Des étapes explicites, des transformations déterministes, des contrôles de validation et des sorties lisibles rapprochent la démo d'un vrai workflow.",
      businessValue: "Valeur métier",
      nextStep: "Prochaine étape",
      similarDataProblem: "Vous avez un problème data similaire ?",
      discussProject: "Discuter d'un projet",
      demoNotFound: "Démo introuvable",
      backToDemos: "Retour aux démos",
      allDemos: "Toutes les démos",
      sourcePrivate: "Code source privé ; la démo navigateur est sûre et synthétique.",
      demoShell: "DemoShell",
      pipelineSimulation: "simulation de pipeline",
      browserLogic: "logique navigateur",
      syntheticDataset: "Jeu de données de démonstration — synthétique · aucun identifiant externe",
      running: "En cours",
      warning: "Attention",
      ready: "Prêt",
      tenant: "Tenant",
      scenario: "Scénario",
      runSimulation: "Lancer la simulation",
      simulationRunning: "Simulation en cours…",
      reset: "Réinitialiser",
      instantResult: "Résultat instantané",
      dataset: "Jeu de données",
      pipelineStatus: "État du pipeline",
      reviewRequired: "Revue requise avant publication",
      syntheticRun: "Exécution synthétique terminée",
      outputPreview: "Aperçu de sortie",
      executionLog: "Journal d'exécution",
      whatHappened: "Que s'est-il passé ?",
      purpose: "Objectif",
      validation: "Validation",
      outputs: "Sorties",
      linkedinProfile: "Profil vérifié LinkedIn",
      experienceCredentials: "Expérience, formation et certifications avec des données sources réelles.",
      headline: "Titre",
      openTo: "Ouvert à",
      viewSource: "Voir le profil source",
      professionalTimeline: "Parcours professionnel",
      rolesContext: "Rôles et contexte de livraison.",
      education: "Formation",
      educationFoundation: "Les fondations derrière le travail.",
      certifications: "Certifications",
      learningMilestones: "Étapes de formation vérifiées.",
      linkedInProjects: "Projets LinkedIn",
      connectedProjects: "Projets reliés au profil.",
      profile: "Profil",
      focusAreas: "Domaines d'intervention",
      focusAreasText: "Data Engineering, Business Intelligence, ETL/ELT, SQL, Snowflake, Power BI, Metabase, automatisation Python et livraison de produits full-stack.",
      downloadCv: "Télécharger le CV",
      backToPortfolio: "Retour au portfolio",
      contactEyebrow: "Contact",
      github: "GitHub",
      linkedin: "LinkedIn",
      email: "Email",
      footerTagline: "Data Engineer | BI Developer | Builder Full-Stack."
      ,homeNode: "Accueil", aboutNode: "À propos", projectsNode: "Projets", articlesNode: "Articles", contactNode: "Contact", resumeNode: "CV", profilesNode: "Profils",
      firstImpression: "01 · première impression", contextNode: "02 · contexte", proofOfWork: "03 · preuves", thinking: "04 · réflexion", startConversation: "05 · démarrer une conversation", credentials: "06 · références", publicCode: "07 · code public",
      heroSection: "Section hero", valueProposition: "Proposition de valeur", primaryCtas: "Actions principales", presentation: "Présentation", experience: "Expérience", toolsSkills: "Outils et compétences", featuredProjects: "Projets sélectionnés", labsInProgress: "Labs / en cours", caseStudies: "Études de cas", blogPosts: "Articles de blog", researchNotes: "Notes de recherche", tutorials: "Tutoriels", message: "Message", collaboration: "Collaboration", workOpportunities: "Opportunités", onePageCv: "CV une page", downloadPdf: "Télécharger le PDF", githubProfile: "Profil GitHub", linkedinProfileLink: "Profil LinkedIn", sourceCode: "Code source", runLiveDemos: "Lancer les démos", followers: "Abonnés LinkedIn", connections: "Relations professionnelles", verifiedRoles: "Rôles et stages vérifiés", kicker: "Data engineering · analytique · architecture BI", agadirMorocco: "AGADIR · MAROC", openToInternational: "OUVERT AU ROYAUME-UNI ET À L'INTERNATIONAL · SUR SITE · HYBRIDE · À DISTANCE", values: "Valeurs", privacyAnalytics: "Le site peut stocker des statistiques de navigation basiques lorsque la base est configurée. Aucun secret client n'est exposé. Les notifications email sont envoyées uniquement lorsqu'un fournisseur est configuré.", presentationBody: "La personne derrière les systèmes, les principes et le style de livraison.", experienceBody: "Un parcours de data, BI, analytique et ingénierie appliquée.", toolsSkillsBody: "La stack pratique utilisée pour les pipelines, warehouses, dashboards et produits.", aboutIntersection: "Son travail se situe à l'intersection de la donnée opérationnelle, de l'analytics engineering, des dashboards et des applications full-stack qui rendent la donnée plus fiable et plus utile.", insightsPageTitle: "Articles techniques, notes et idées de recherche.", loadingArticle: "Chargement de l'article...", rows: "lignes", columns: "colonnes"
    }
  }
};

type LanguageContextValue = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: typeof dictionary.en;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("lang") as Lang) || "en");
  const value = useMemo(() => ({
    lang,
    setLang: (next: Lang) => {
      localStorage.setItem("lang", next);
      setLang(next);
    },
    t: dictionary[lang]
  }), [lang]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
